name: devtoys
version: 1.0.0+1
publish_to: none
description: A Swiss Army knife for developers.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  flutter: 
    sdk: flutter
  yaru: ^0.3.3
  yaru_widgets: ^1.1.2
  get: ^4.6.5
  layout: ^1.0.3
  auto_size_text: ^3.0.0
  font_awesome_flutter: ^10.2.1
  code_text_field: ^1.0.2
  resizable_widget: ^1.0.5
  yaru_colors: ^0.1.0
  html_unescape: ^2.0.0
  flutter_markdown: ^0.6.12
  pretty_diff_text: ^1.0.0
  xml: ^6.1.0

dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true

