name: Build AppImage

on:
  push:
    branches:
      - main

jobs:  
  build_appimage:
    name: Build AppImage
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Dependencies
      run: sudo apt update && sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
      
    - name: Cache Flutter dependencies
      uses: actions/cache@v1
      with:
        path: /opt/hostedtoolcache/flutter
        key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
        
    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable' 
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Test project
      run: flutter test
      
    - name: Build
      run: flutter build linux --release
        
    - name: Build AppImage
      run: |
        cp -r build/linux/x64/release/bundle DevWidgets.AppDir
        wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x ./appimagetool-x86_64.AppImage
        cp -r linux/appimage_assets/* DevWidgets.AppDir/
        chmod +x DevWidgets.AppDir/AppRun
        ./appimagetool-x86_64.AppImage DevWidgets.AppDir/

    - name: Upload .AppImage artifact to workflow
        uses: actions/upload-artifact@v2
        with:
          name: AppImage artifact
          path: DevWidgets-x86_64.AppImage
