name: Build Flatpak

on:
  push:
    branches:
      - main

jobs:
  build-flutter-app:
    name: Build and compressed Flutter app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: sudo apt update && sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
        
      - name: Cache Flutter dependencies
        uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
          
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' 

      - name: Build
        run: |
          flutter pub get
          flutter build linux

      - name: Compress Flutter build
        run: tar -C build/linux/x64/release/bundle -cvf DevWidgets-Linux-Portable.tar.gz .

      - name: Upload app archive for next steps
        uses: actions/upload-artifact@v2
        with:
          name: DevWidgets-Archive
          path: DevWidgets-Linux-Portable.tar.gz

  build-flatpak:
    name: Build flatpak
    needs: build-flutter-app
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-21.08
      options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download app archive
        uses: actions/download-artifact@v3
        with:
          name: DevWidgets-Archive

      - name: Build .flatpak
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
        with:
          bundle: DevWidgets.flatpak
          manifest-path: br.com.barros.DevWidgets.json

      - name: Upload .flatpak artifact to workflow
        uses: actions/upload-artifact@v2
        with:
          name: Flatpak artifact
          path: DevWidgets.flatpak