name: Build Windows

on:
  push:
    branches:
      - main

jobs:
  build-windows-msix:
    name: Build Windows .msix
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' 

      - name: Get dependencies
        run: flutter pub get

      - name: Build
        run: flutter pub run msix:create

      - name: Upload .msix for release
        uses: actions/upload-artifact@v2
        with:
          name: Windows artifact
          path: build/windows/runner/Release/DevWidgets.msix
